# 背景模糊
# 在Macos下开启会导致窗口阴影不渲染，不太和谐，所以不用
# background_opacity 0.90
background_opacity 1.0
dynamic_background_opacity false
background_blur 60

allow_hyperlinks yes
clipboard_control write-clipboard write-primary read-clipboard read-primary
# titlebar
macos_titlebar_color background
macos_show_window_title_in menubar
# hide_window_decorations titlebar-only
# tab_bar_background none

# 
allow_remote_control yes
# enabled_layouts=tall
enabled_layouts horizontal

# window_padding_width 0 8
window_padding_width 0 8 8 8 
# top, right, bottom and left.
# window_padding_width 5 8

remember_window_size  no
initial_window_width  85c
initial_window_height 35c
 # suffix of "c" on the value means "character cell" instead of pixels
# draw_minimal_borders yes

# 光标动画 
cursor_trail 1
# 始终启用光标轨迹
cursor_trail_start_threshold -1 
cursor_trail_decay 0.1 0.15 

cursor_blink_interval 0.5

scrollback_lines 10000

macos_option_as_alt yes

# Vi mode
# scrollback_pager nvim -c "lua require('kitty+page')(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN, KITTY_WINDOW_ID)"
# scrollback_pager nvim -u NONE -R -M -c 'lua require("kitty+page")(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)' - 
# scrollback_pager nvim -u NONE -R -M -c "lua require('kitty+page')(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN, KITTY_WINDOW_ID)" - 
scrollback_pager nvim -u NONE -R -M -c "lua require('kitty+page')(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN, KITTY_WINDOW_ID)" - 
map shift+ctrl+x show_scrollback

font_size 14
# line_height 1.2
 # narrow_symbols U+E0A0-U+E0A3,U+E0C0-U+E0C7 1 
# narrow_symbols  2 
modify_font cell_height +120%
modify_font cell_width +0px
modify_font baseline 95%

# BEGIN_KITTY_FONTS
# font_family      family="JetBrainsMono Nerd Font"
# font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto 
# symbol_map U+E000-U+F8FF Symbols Nerd Font Mono
# Nerd Fonts v3.3.0 的符号范围（官方给的清单）
# symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Hardcore
include current-theme.conf
# END_KITTY_THEME
