{ isDarwin, isWsl, ... }: {
  modules = {
    aerospace.enable = isDarwin;
    aichat.enable = true;
    astronvim.enable = true;
    browser.enable = !isWsl;
    btop.enable = true;
    cli.core.enable = true;
    cli.desktop.enable = true;
    dev.enable = true;
    eza.enable = true;
    fd.enable = true;
    fish.enable = true;
    freecad.enable = true;
    ghostty.enable = !isWsl;
    git.enable = true;
    gui.enable = !(isDarwin || isWsl);
    kitty.enable = true;
    lazygit.enable = true;
    lazyvim.enable = true;
    lsd.enable = true;
    mpv.enable = !isWsl;
    neovim.enable = true;
    neovide.enable = true;
    opencode.enable = true;
    shell.enable = true;
    ssh.enable = true;
    starship.enable = true;
    tmux.enable = true;
    vscode.enable = true;
    wayland.enable = !(isDarwin || isWsl);
    wezterm.enable = !isDarwin;
    xdg.enable = !isDarwin;
    yazi.enable = true;
    zathura.enable = !isWsl;
    zellij.enable = true;
    zsh.enable = true;
  };
}
