---@type NvPluginSpec
return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = { "nvim-treesitter/nvim-treesitter-textobjects", "nvim-treesitter/playground" },
  opts = {
    ensure_installed = {
      "php",
      "vim",
      "lua",
      "vimdoc",
      "html",
      "http",
      "css",
      "vue",
      "bash",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "toml",
      "luadoc",
      "python",
      "typescript",
      "javascript",
      "diff",
      "jsdoc",
      "json",
      "jsonc",
      "c",
      "cpp",
      "tsx",
      "markdown",
      "markdown_inline",
      "latex",
      "rust",
      "zig",
      "xml",
      "yaml",
      "asm",
      "regex",
      "query",
      "printf",
      "luap",

      "zig",
    },
    auto_install = true,
    indent = { enable = true },
    highlight = { enable = true },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<C-space>",
        node_incremental = "<C-space>",
        scope_incremental = false,
        node_decremental = "<bs>",
      },
    },
    textobjects = {
      move = {
        enable = true,
        goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer", ["]a"] = "@parameter.inner" },
        goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer", ["]A"] = "@parameter.inner" },
        goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer", ["[a"] = "@parameter.inner" },
        goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer", ["[A"] = "@parameter.inner" },
      },
    },
    query_linter = {
      enable = true,
      use_virtual_text = true,
      lint_events = { "BufWrite", "CursorHold" },
    },
  },
}
